<script>
/* =====================================================================
   SOLVED STRATEGY: loading, lookup, and the bot that plays it.

   Everything in the first half of this file is a port of solver/src/abstraction.rs and
   MUST stay bit-identical to it. If the two disagree the bot reads the wrong row of the
   strategy table and plays nonsense, silently. verifySolverAbstraction() checks the port
   against 4,000 samples generated by the Rust binary itself.
   ===================================================================== */

const SOLVER = {
  tree: null,        // parsed strategy.json
  byDepth: {},       // depth -> {nodes, root, keyMap, strat:Map(nodeIdx -> Map(state->Uint8Array))}
  ready: false,
  misses: 0, hits: 0
};

/* ---------- port of abstraction.rs ---------- */
const N_BUCKET_JS = 216;

function jsPreflopClass(hole){
  const r1=rankOf(hole[0]), r2=rankOf(hole[1]);
  const suited = suitOf(hole[0])===suitOf(hole[1]);
  const hi=Math.max(r1,r2), lo=Math.min(r1,r2);
  if(hi===lo) return hi;
  let k=0;
  for(let a=1;a<NRANK;a++) for(let b=0;b<a;b++){
    if(a===hi && b===lo) return 9 + 2*k + (suited?0:1);
    k++;
  }
  throw new Error("bad hole");
}

function jsTexture(board){
  const sc=[0,0,0,0], rc=new Array(NRANK).fill(0);
  for(const c of board){ sc[suitOf(c)]++; rc[rankOf(c)]++; }
  const maxs=Math.max(...sc);
  const suitcat = maxs>=4?2:(maxs===3?1:0);
  const paired = rc.some(n=>n>=2)?1:0;
  return suitcat*2+paired;
}

function jsStraightDraw(mask){
  let outs=0;
  for(const [m] of STRAIGHT_MASKS){
    let have=0;
    for(let r=0;r<NRANK;r++) if((m>>r&1) && (mask>>r&1)) have++;
    if(have===4) outs |= (m & ~mask);
  }
  let n=0; for(let r=0;r<NRANK;r++) if(outs>>r&1) n++;
  return n===0?0:(n===1?1:2);
}

function jsFlushDraw(board, hole){
  const sc=[0,0,0,0];
  for(const c of board) sc[suitOf(c)]++;
  for(const c of hole) sc[suitOf(c)]++;
  return sc.some(n=>n===4)?1:0;
}

function jsStrengthBin(hole, board, cat){
  const boardScore = score(board);
  const brc = new Array(NRANK).fill(0);
  for(const c of board) brc[rankOf(c)]++;
  const branks = board.map(rankOf);
  const bmax = Math.max(...branks), bmin = Math.min(...branks);

  if(cat === HIGH){
    let over=0; for(const c of hole) if(rankOf(c)>bmax) over++;
    return Math.min(over,2);
  }
  if(cat === PAIR){
    const rc = brc.slice();
    for(const c of hole) rc[rankOf(c)]++;
    let pr=0;
    for(let r=NRANK-1;r>=0;r--) if(rc[r]===2){ pr=r; break; }
    if(brc[pr]>=2) return 0;
    if(pr>bmax) return 3;
    if(pr===bmax) return 2;
    if(pr>bmin) return 1;
    return 0;
  }
  const mine = score(board.concat(hole));
  if(mine === boardScore) return 0;
  if(cat >= STRAIGHT) return 3;
  if(rankOf(hole[0])===rankOf(hole[1]) && cat===TRIPS) return 3;
  return 2;
}

function jsPostflopState(hole, board){
  const cards = board.concat(hole);
  const cat = score(cards)>>20;
  const strength = jsStrengthBin(hole, board, cat);
  let fd=0, sd=0;
  if(!(board.length>=5 || cat>=FLUSH)){
    let mask=0; for(const c of cards) mask |= 1<<rankOf(c);
    fd = jsFlushDraw(board, hole);
    sd = jsStraightDraw(mask);
  }
  const bucket = cat*24 + strength*6 + fd*3 + sd;
  return jsTexture(board)*N_BUCKET_JS + bucket;
}

/* ---------- verification against the Rust output ---------- */
async function verifySolverAbstraction(){
  const r = await fetch("data/abstraction_check.json", {cache:"no-cache"});
  if(!r.ok) return {ok:false, reason:"abstraction_check.json not found"};
  const rows = await r.json();
  let bad = [];
  for(const row of rows){
    const hole = parseCards(row.hole), b = parseCards(row.board);
    const got = {
      pf: jsPreflopClass(hole),
      flop: jsPostflopState(hole, b.slice(0,3)),
      turn: jsPostflopState(hole, b.slice(0,4)),
      river: jsPostflopState(hole, b.slice(0,5))
    };
    for(const k of ["pf","flop","turn","river"]){
      if(got[k]!==row[k]){
        bad.push(`${row.hole} on ${row.board} ${k}: js=${got[k]} rust=${row[k]}`);
        break;
      }
    }
    if(bad.length>6) break;
  }
  return {ok:bad.length===0, checked:rows.length, bad};
}
window.verifySolverAbstraction = verifySolverAbstraction;

/* ---------- loading ---------- */
async function loadSolver(){
  const rj = await fetch("data/strategy.json", {cache:"no-cache"});
  if(!rj.ok) return false;
  const tree = await rj.json();
  const rb = await fetch("data/" + (tree.strategyFile||"strategy.bin"), {cache:"no-cache"});
  if(!rb.ok) return false;
  const buf = new Uint8Array(await rb.arrayBuffer());
  const dv = new DataView(buf.buffer);

  if(String.fromCharCode(buf[0],buf[1],buf[2],buf[3]) !== "SDS1")
    throw new Error("strategy.bin: bad magic");
  let p = 4;
  const nDepths = dv.getUint32(p, true); p += 4;

  SOLVER.tree = tree;
  SOLVER.byDepth = {};
  for(let d=0; d<nDepths; d++){
    const depth = dv.getInt32(p, true); p += 4;
    const meta = tree.depths.find(x=>x.depth===depth);
    if(!meta) throw new Error("strategy.bin depth "+depth+" not in strategy.json");
    const strat = new Map();
    for(;;){
      const nodeIdx = dv.getUint32(p, true); p += 4;
      if(nodeIdx === 0xFFFFFFFF) break;
      const nRows = dv.getUint32(p, true); p += 4;
      const nact = meta.nodes[nodeIdx].a.length;
      const m = new Map();
      for(let i=0;i<nRows;i++){
        const st = dv.getUint16(p, true); p += 2;
        m.set(st, buf.subarray(p, p+nact)); p += nact;
      }
      strat.set(nodeIdx, m);
    }
    /* Two indexes. The exact one finds the node for an identical betting state. The
       grouped one is for the case that cannot be avoided: real stacks drift off the
       10/15/20/... grid, so a jam for 47.0A has no exact twin in the 50A tree. Then we
       take the node with the same shape and the closest amounts. */
    const keyMap = new Map();
    const groups = new Map();
    meta.nodes.forEach((n,i)=>{
      if(n.k!=="D") return;
      keyMap.set(n.st.join(","), i);
      const g = [n.st[0],n.st[1],n.st[6],n.st[7],n.st[8]].join(",");
      if(!groups.has(g)) groups.set(g, []);
      groups.get(g).push({i, c0:n.st[2], c1:n.st[3], sb0:n.st[4], sb1:n.st[5]});
    });
    SOLVER.byDepth[depth] = {meta, strat, keyMap, groups};
  }
  SOLVER.ready = true;
  return true;
}
window.loadSolver = loadSolver;

/* ---------- lookup ---------- */
const SOLVER_DEPTHS = [10,15,20,30,40,50,65,80,100];
function nearestDepth(effA){
  let best=SOLVER_DEPTHS[0];
  for(const d of SOLVER_DEPTHS) if(Math.abs(d-effA)<Math.abs(best-effA)) best=d;
  return best;
}
/* solver seat 0 is always the BUTTON */
const solverSeat = s => (s===G.button ? 0 : 1);
const t10 = v => Math.round(v*10);

function solverStateVec(){
  const b = G.button, nb = 1-b;     // solver seat 0 is the button
  return [
    G.street,
    solverSeat(G.toAct),
    t10(G.committed[b]), t10(G.committed[nb]),
    t10(G.streetBet[b]), t10(G.streetBet[nb]),
    G.betsThisStreet,
    G.lastAgg,
    G.actorsToAct,
    t10(G.minRaiseInc)
  ];
}
function solverKey(){ return solverStateVec().join(","); }

/* Find the node for the current spot. Exact match first; otherwise the closest node of
   the same shape, which is what rescues hands played at a stack size between grid points
   (a 47A jam against the 50A tree). Returns -1 if nothing close enough exists. */
function findNode(D){
  const v = solverStateVec();
  const exact = D.keyMap.get(v.join(","));
  if(exact !== undefined) return exact;
  const g = D.groups.get([v[0],v[1],v[6],v[7],v[8]].join(","));
  if(!g) return -1;
  let best=-1, bestd=Infinity;
  for(const n of g){
    const d = Math.abs(n.c0-v[2]) + Math.abs(n.c1-v[3])
            + Math.abs(n.sb0-v[4]) + Math.abs(n.sb1-v[5]);
    if(d < bestd){ bestd = d; best = n.i; }
  }
  /* refuse a match that is not really the same spot */
  const pot = v[2] + v[3];
  return bestd <= Math.max(20, pot * 0.25) ? best : -1;
}

/* Returns a JS action chosen by the solved strategy, or null if this spot is not in the
   solved tree (then the caller falls back to the heuristic bot). */
function solverChoose(seat){
  if(!SOLVER.ready) return null;
  const depth = nearestDepth(G.effStart);      // stack depth as the hand STARTED
  const D = SOLVER.byDepth[depth];
  if(!D) return null;
  const idx = findNode(D);
  if(idx < 0){ SOLVER.misses++; return null; }
  const node = D.meta.nodes[idx];
  const state = G.street===0
      ? jsPreflopClass(G.hole[seat])
      : jsPostflopState(G.hole[seat], G.board.slice(0, G.street===1?3:(G.street===2?4:5)));
  const rows = D.strat.get(idx);
  const row = rows && rows.get(state);
  if(!row){ SOLVER.misses++; return null; }
  SOLVER.hits++;

  let tot=0; for(const v of row) tot+=v;
  if(tot<=0){ SOLVER.misses++; return null; }
  let r = Math.random()*tot, pick=0;
  for(let i=0;i<row.length;i++){ r-=row[i]; if(r<=0){ pick=i; break; } }

  const a = node.a[pick];
  const legal = legalActions(seat);
  switch(a[0]){
    case "f": return legal.find(x=>x.t==="fold") || legal[0];
    case "x": return legal.find(x=>x.t==="check") || legal[0];
    case "c": return legal.find(x=>x.t==="call") || legal.find(x=>x.t==="check") || legal[0];
    case "r": {
      const to = a[1]/10;
      const raises = legal.filter(x=>x.t==="raise");
      if(!raises.length) return legal.find(x=>x.t==="call") || legal[0];
      /* pick the legal raise closest to what the solver wants */
      return raises.reduce((best,x)=>
        Math.abs(x.to-to) < Math.abs(best.to-to) ? x : best, raises[0]);
    }
  }
  return null;
}
window.solverChoose = solverChoose;
</script>
